name: Official Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Exact version to release
        required: true
        type: string
      release_version_type:
        description: Version type for Modrinth
        required: true
        type: choice
        default: release
        options:
          - release
          - beta
          - alpha

jobs:
  call_build:
    uses: ./.github/workflows/reusable_build.yml
    permissions:
      contents: write
      packages: write
    with:
      is-release-build: true
      release-version: ${{ inputs.release_version }}
      release-version-type: ${{ inputs.release_version_type }}
      publish-artifacts: true
    secrets: inherit